// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArd4DYbPLKNdCeRxLezs-CScQBnxKG8Y4',
    appId: '1:700569603795:web:934751b458250c5cd9ce26',
    messagingSenderId: '700569603795',
    projectId: 'flutter-push-notificatio-7bf7c',
    authDomain: 'flutter-push-notificatio-7bf7c.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-7bf7c.appspot.com',
    measurementId: 'G-X45QW9253Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwCDa5DK6UbA_xqP_rCQyKwD0gY073iH4',
    appId: '1:700569603795:android:5c159e8dc1919f99d9ce26',
    messagingSenderId: '700569603795',
    projectId: 'flutter-push-notificatio-7bf7c',
    storageBucket: 'flutter-push-notificatio-7bf7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgAS0n-yVB0QmNfi2VixhY4ocArmUBQ3I',
    appId: '1:700569603795:ios:a5a7e6ef4d246d9cd9ce26',
    messagingSenderId: '700569603795',
    projectId: 'flutter-push-notificatio-7bf7c',
    storageBucket: 'flutter-push-notificatio-7bf7c.appspot.com',
    iosBundleId: 'com.example.flutterPushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgAS0n-yVB0QmNfi2VixhY4ocArmUBQ3I',
    appId: '1:700569603795:ios:a5a7e6ef4d246d9cd9ce26',
    messagingSenderId: '700569603795',
    projectId: 'flutter-push-notificatio-7bf7c',
    storageBucket: 'flutter-push-notificatio-7bf7c.appspot.com',
    iosBundleId: 'com.example.flutterPushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArd4DYbPLKNdCeRxLezs-CScQBnxKG8Y4',
    appId: '1:700569603795:web:4dece05d392bb9f1d9ce26',
    messagingSenderId: '700569603795',
    projectId: 'flutter-push-notificatio-7bf7c',
    authDomain: 'flutter-push-notificatio-7bf7c.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-7bf7c.appspot.com',
    measurementId: 'G-PE02FHRDT6',
  );
}
